import { ArrowLeft, Eye, EyeOff, LockKeyhole, Mail } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { Brand } from "../components/Brand";
import { useAuth } from "../context/AuthContext";

function AuthFrame({ children, title, copy }: { children: React.ReactNode; title: string; copy: string }) { return <div className="auth-page"><div className="auth-visual"><Brand /><div><span className="eyebrow">Size ait bir alan</span><blockquote>“İnsan bazen ancak yazarken kendine yetişir.”</blockquote><p>Günlükleriniz güçlü şifreleme ile saklanır.</p></div></div><main className="auth-main"><Link className="back-link" to="/"><ArrowLeft /> Ana sayfa</Link><section className="auth-form"><h1>{title}</h1><p>{copy}</p>{children}</section></main></div>; }

export function LoginPage() {
  const { session, login } = useAuth(); const navigate = useNavigate(); const [show,setShow]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  if (session) return <Navigate to="/app/gunluk" replace />;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data=new FormData(event.currentTarget); setBusy(true); setError(""); try { await login(String(data.get("identifier")),String(data.get("password"))); navigate("/app/gunluk"); } catch(e){setError((e as Error).message);} finally{setBusy(false);} };
  return <AuthFrame title="Tekrar hoş geldiniz." copy="Kaldığınız sayfadan devam edin."><form onSubmit={submit}><label>E-posta veya yönetici kullanıcı adı<div className="input-wrap"><Mail /><input name="identifier" required autoComplete="username" /></div></label><label>Şifre<div className="input-wrap"><LockKeyhole /><input name="password" required type={show?"text":"password"} autoComplete="current-password" /><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Şifreyi gizle":"Şifreyi göster"}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?"Giriş yapılıyor...":"Giriş yap"}</button></form><p className="auth-switch">Hesabınız yok mu? <Link to="/kayit">Kayıt olun</Link></p></AuthFrame>;
}

export function RegisterPage() {
  const { session, register } = useAuth(); const navigate=useNavigate(); const [accepted,setAccepted]=useState(false); const [kvkk,setKvkk]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  if(session) return <Navigate to="/app/gunluk" replace/>;
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault(); const data=new FormData(event.currentTarget); if(data.get("password")!==data.get("confirm")) return setError("Şifreler eşleşmiyor."); setBusy(true); setError(""); try{await register(String(data.get("email")),String(data.get("password")));navigate("/app/gunluk");}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <AuthFrame title="İlk sayfanızı açın." copy="Sakin ve yalnızca size ait bir alan oluşturun."><form onSubmit={submit}><label>E-posta<div className="input-wrap"><Mail/><input name="email" type="email" required autoComplete="email"/></div></label><label>Şifre<div className="input-wrap"><LockKeyhole/><input name="password" type="password" required minLength={10} autoComplete="new-password"/></div><small>En az 10 karakter, bir büyük harf ve bir rakam.</small></label><label>Şifreyi tekrar edin<div className="input-wrap"><LockKeyhole/><input name="confirm" type="password" required autoComplete="new-password"/></div></label><label className="consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span><button type="button" onClick={()=>setKvkk(true)}>KVKK Aydınlatma Metni</button>'ni okudum ve kişisel verilerimin belirtilen amaçlarla işlenmesini kabul ediyorum.</span></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={!accepted||busy}>{busy?"Hesap oluşturuluyor...":"Kayıt ol"}</button></form><p className="auth-switch">Zaten hesabınız var mı? <Link to="/giris">Giriş yapın</Link></p>{kvkk&&<KvkkModal onClose={()=>setKvkk(false)}/>}</AuthFrame>;
}

function KvkkModal({onClose}:{onClose():void}) { return <div className="modal-overlay" role="dialog" aria-modal="true" aria-labelledby="kvkk-title"><section className="legal-modal"><button className="icon-button modal-close" onClick={onClose} aria-label="Metni kapat">×</button><h2 id="kvkk-title">KVKK Aydınlatma Metni Taslağı</h2><p>Sırdaş AI; hesabınızı ve kişisel günlük hizmetini sunmak için e-posta adresinizi, geri döndürülemez parola özetinizi, günlük metinlerinizi ve varsa oluşturulan analizleri işler.</p><p>Günlük ve analiz içerikleri sunucu tarafında şifrelenerek saklanır. AI analizi etkinleştirildiğinde günlük metniniz analiz amacıyla yapılandırılmış yapay zeka sağlayıcısına gönderilir. Sağlayıcı bilgisi etkinleştirmeden önce bu metinde güncellenecektir.</p><p>Veriler hizmetin sunulması, güvenliği ve sizin talep ettiğiniz geçmiş görünümünün oluşturulması için saklanır. Verilerinizi dışa aktarma, düzeltme ve hesabınızla birlikte kalıcı olarak silme hakkınız vardır.</p><p>İletişim: Uygulamanın Ayarlar bölümünde yapılandırılmış veri sorumlusu iletişim adresi gösterilir.</p><p className="medical-note">Bu taslak hukuki danışmanlık değildir; gerçek kullanıcılarla yayına alınmadan önce bir hukukçu tarafından incelenmelidir.</p><button className="button primary" onClick={onClose}>Metni okudum</button></section></div>; }
