import { motion, useScroll, useTransform } from "framer-motion";
import { ArrowRight, BookHeart, Brain, LockKeyhole, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { Brand } from "../components/Brand";

export function LandingPage() {
  const { scrollYProgress } = useScroll(); const opacity = useTransform(scrollYProgress, [0, .18], [1, 0]); const y = useTransform(scrollYProgress, [0, .18], [0, -70]);
  return <div className="landing">
    <header className="topbar"><Brand /><nav><Link to="/giris">Giriş yap</Link><Link className="button primary" to="/kayit">Başla <ArrowRight size={17} /></Link></nav></header>
    <section className="hero"><div className="hero-shade" /><motion.div className="hero-copy" style={{ opacity, y }}><span className="eyebrow">Kendinle sessiz bir buluşma</span><h1>Sırdaş AI</h1><p>İçinden geçenleri yaz. Günün, kelimelerinin arasından sana daha yakından görünsün.</p><div className="hero-actions"><Link className="button primary" to="/kayit">İlk sayfanı aç <ArrowRight /></Link><Link className="button ghost-light" to="/giris">Giriş yap</Link></div></motion.div><a className="scroll-cue" href="#nasil">Keşfet<span /></a></section>
    <section id="nasil" className="section how"><div className="section-heading"><span className="eyebrow">Nasıl çalışır?</span><h2>Bir gün, birkaç satır, daha berrak bir bakış.</h2></div><div className="steps">{[[BookHeart,"Yaz","Gününüzü acele etmeden kendi kelimelerinizle anlatın."],[Brain,"Dinle","Analiz açıldığında Sırdaş AI, yargılamadan örüntüleri yansıtır."],[Sparkles,"Kendine dön","Size uygun küçük ve uygulanabilir adımları görün."]].map(([Icon,title,text], index) => { const C = Icon as typeof BookHeart; return <motion.article key={String(title)} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.12}}><span>0{index+1}</span><C /><h3>{String(title)}</h3><p>{String(text)}</p></motion.article>;})}</div></section>
    <section className="section privacy-band"><div><span className="eyebrow">Size ait, size yakın</span><h2>Günlüğünüz bir veri noktası değil, kişisel alanınızdır.</h2></div><div className="privacy-points"><p><LockKeyhole /> Günlükler sunucuda şifreli saklanır.</p><p><Brain /> Yönetici yalnızca anonim toplamları görür.</p><p><BookHeart /> İçeriğinizi dışa aktarabilir veya tamamen silebilirsiniz.</p></div></section>
    <section className="section benefits"><div className="section-heading"><span className="eyebrow">Yazmanın bıraktığı iz</span><h2>Kelimeler bazen zihnin tutamadığını düzenler.</h2><p>Düzenli günlük tutmak; duyguları adlandırmaya, yaşananları farklı bir açıdan görmeye ve kişisel örüntüleri fark etmeye yardımcı olabilir. Sırdaş AI bu alışkanlığa sakin, özel ve ölçülü bir alan açar.</p></div><div className="benefit-list"><article><strong>01</strong><h3>Öz farkındalık</h3><p>Günün içinde görünmeyen duygular, yazıda daha anlaşılır bir biçim alabilir.</p></article><article><strong>02</strong><h3>Duygu düzenleme</h3><p>Düşünceleri dışarı aktarmak, yoğunluğu azaltıp bir sonraki adımı seçmeyi kolaylaştırabilir.</p></article><article><strong>03</strong><h3>Hatırlama ve gelişim</h3><p>Zaman içindeki değişimi kendi kelimelerinizden okumak, ilerlemeyi görünür kılar.</p></article></div></section>
    <section className="final-cta"><BookHeart /><h2>Bugünün sayfası sizi bekliyor.</h2><p>Kendinize birkaç dürüst cümle ayırın.</p><Link className="button primary" to="/kayit">Ücretsiz hesap oluştur <ArrowRight /></Link></section>
    <footer><Brand /><p>© 2026 Sırdaş AI. Bir tanı veya tedavi hizmeti değildir.</p></footer>
  </div>;
}
